pipeline {
    agent any
    stages {
        stage ('Check Apache') {
            steps {
                dir ('losson_12') {
                    sh 'bash status.sh'
                }
            }
        }
    }
}